version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_marketplace_two_developers
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: 'bitnami/postgresql:latest'
    container_name: marketplace_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=laravelmarketplace
      - POSTGRES_USER=twodevelopers
      - POSTGRES_PASSWORD=zxcv123
    volumes:
      - pgdata:/bitnami/postgresql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - laravel

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: